version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8484:8484
    volumes:
      - ./frontend:/app
      # exclude volumes
      - /app/node_modules
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8383 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - 8383:8383
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - app-db-volume:/var/lib/mysql
    ports:
      - "8306:3306"
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
volumes:
  app-db-volume: